apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-mongo
  labels:
    name: data-mongo # name can be anything
spec:
  storageClassName: nfs-mongo # same storage class as pvc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.160 # ip addres of nfs server
    path: "/app-mongo/data" # path to directory

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-mongo
spec:
  storageClassName: nfs-mongo
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 1Gi