#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: nfs-pv-postgres
#  labels:
#    name: data-postgres # name can be anything
#spec:
#  storageClassName: manual-postgres # same storage class as pvc
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  nfs:
#    server: 192.168.1.160 # ip address of nfs server
#    path: "/srv/nfs4/pdata" # path to directory
#
#---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-postgres
spec:
  storageClassName: manual-postgres
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 1Gi