# ansible-playbook check-servers.yml --ask-vault --extra-vars '@passwd.yml'
- hosts: all
  become: yes
  tasks:
    - name: Ping Servers
      shell: uname -a
      register: results
      check_mode: no
      tags: ping
    - name: Print Server Status
      debug:
        msg:
          - "Server Status: {{results.stdout}}"
      when: results != ""
      tags: print-status
