# Check user account status
- hosts: base
  become: true
  gather_facts: false
  vars:
    users:
      - "foop"
      - "tnaw"
      - "ff"

  tasks:
    - name: Check User Account Status
      command: sh /home/tnaw/A2T/dev/devops-ansible-kubernetes/ansible/scripts/get-user-status.sh "{{ item }}"
      register: out
      with_items: "{{ users }}"
      check_mode: no
      ignore_errors: true

    - name: print out put
      debug:
        msg: "{{ out.results | map(attribute='stdout_lines') | list }}"


