# Check user account status
- hosts: base
  become: true
  gather_facts: false
  vars:
    users:
      - "user1"
      - "user2"
      - "user3"

  tasks:
    - name: Check User Account Status
      shell: if id "{{ item }}" &>/dev/null; then echo "====== {{ item }} : $(hostname) ======" && id "{{ item }}" && chage -l "{{ item }}"; else echo "====== NOT FOUND {{ item }} : $(hostname) ======"; fi
      #script: /some/location/devops-ansible-kubernetes/ansible/scripts/get-user-status.sh "{{ item }}"
      register: out
      with_items: "{{ users }}"
      check_mode: no
      ignore_errors: true

    - name: Print Status
      debug:
        msg: "{{ out.results | map(attribute='stdout') | list }}"


