# ansible-playbook tomcat.yml --ask-vault --extra-vars '@passwd.yml' --tags=restart
- hosts: web
  become: true
  tasks:
    - name: restart tomcat
      service: name=tomcat state=restarted
      tags: restart
    - name: stop tomcat
      service: name=tomcat state=stopped
      tags: stop

